import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";

type Props = {
  onClick: (mintNum: number) => void;
};

const HomeTemplate: React.FC<Props> = (props) => {
  const [mintNum, setMintNum] = React.useState<number>(1);

  const plus = () => {
    const mint = mintNum + 1;
    setMintNum(mint);
  };
  const minus = () => {
    const mint = mintNum - 1;
    setMintNum(mint);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <div>Generated NFT Practice </div>
        </h1>
        <div className={styles.numberSelect}>
          <div className={styles.minus} onClick={minus}>
            -
          </div>
          <div className={styles.plus} onClick={plus}>
            ＋
          </div>
        </div>
        <div>MINT NUM : {mintNum}</div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Mint NFT &rarr;</h2>
            <div onClick={() => props.onClick(mintNum)}>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div>
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </div>
      </footer>
    </div>
  );
};

export default HomeTemplate;
